fix(docker): install corepack in slim image
node:current-slim doesn't include corepack by default.
Install it with npm before using it to setup pnpm.

Error: /bin/sh: 1: corepack: not found